
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__dbus_OrgMeumeuBlingAdaptor_h__adaptor__H__
#define __sdbuscpp__dbus_OrgMeumeuBlingAdaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org
{
namespace meumeu
{
class blingdaemon_adaptor
{
public:
	static constexpr const char * INTERFACE_NAME = "org.meumeu.blingdaemon";

protected:
	blingdaemon_adaptor(sdbus::IObject & object) : object_(object)
	{
		object_.registerMethod("CreateImage")
		        .onInterface(INTERFACE_NAME)
		        .withInputParamNames("image")
		        .withOutputParamNames("id")
		        .implementedAs([this](const std::string & image) { return this->CreateImage(image); });
		object_.registerMethod("CreateText")
		        .onInterface(INTERFACE_NAME)
		        .withInputParamNames("text", "font")
		        .withOutputParamNames("id")
		        .implementedAs([this](const std::string & text, const std::string & font) {
			        return this->CreateText(text, font);
		        });
	}

	~blingdaemon_adaptor() = default;

private:
	virtual sdbus::ObjectPath CreateImage(const std::string & image) = 0;
	virtual sdbus::ObjectPath CreateText(const std::string & text, const std::string & font) = 0;

private:
	sdbus::IObject & object_;
};

} // namespace meumeu
} // namespace org

namespace org
{
namespace meumeu
{
class bling_adaptor
{
public:
	static constexpr const char * INTERFACE_NAME = "org.meumeu.bling";

protected:
	bling_adaptor(sdbus::IObject & object) : object_(object)
	{
		object_.registerMethod("AddRotate")
		        .onInterface(INTERFACE_NAME)
		        .withInputParamNames("frames")
		        .implementedAs([this](const std::vector<sdbus::Struct<double, double>> & frames) {
			        return this->AddRotate(frames);
		        });
		object_.registerMethod("AddTranslate")
		        .onInterface(INTERFACE_NAME)
		        .withInputParamNames("frames")
		        .implementedAs([this](const std::vector<sdbus::Struct<double, double, double>> & frames) {
			        return this->AddTranslate(frames);
		        });
		object_.registerMethod("AddScale")
		        .onInterface(INTERFACE_NAME)
		        .withInputParamNames("frames")
		        .implementedAs([this](const std::vector<sdbus::Struct<double, double, double>> & frames) {
			        return this->AddScale(frames);
		        });
		object_.registerMethod("AddBrightness")
		        .onInterface(INTERFACE_NAME)
		        .withInputParamNames("frames")
		        .implementedAs([this](const std::vector<sdbus::Struct<double, double>> & frames) {
			        return this->AddBrightness(frames);
		        });
		object_.registerMethod("AddAlpha")
		        .onInterface(INTERFACE_NAME)
		        .withInputParamNames("frames")
		        .implementedAs([this](const std::vector<sdbus::Struct<double, double>> & frames) {
			        return this->AddAlpha(frames);
		        });
		object_.registerMethod("Show")
		        .onInterface(INTERFACE_NAME)
		        .withInputParamNames("duration", "zorder")
		        .implementedAs([this](const double & duration, const int32_t & zorder) {
			        return this->Show(duration, zorder);
		        });
		object_.registerMethod("Destroy").onInterface(INTERFACE_NAME).implementedAs([this]() {
			return this->Destroy();
		});
	}

	~bling_adaptor() = default;

private:
	virtual void AddRotate(const std::vector<sdbus::Struct<double, double>> & frames) = 0;
	virtual void AddTranslate(const std::vector<sdbus::Struct<double, double, double>> & frames) = 0;
	virtual void AddScale(const std::vector<sdbus::Struct<double, double, double>> & frames) = 0;
	virtual void AddBrightness(const std::vector<sdbus::Struct<double, double>> & frames) = 0;
	virtual void AddAlpha(const std::vector<sdbus::Struct<double, double>> & frames) = 0;
	virtual void Show(const double & duration, const int32_t & zorder) = 0;
	virtual void Destroy() = 0;

private:
	sdbus::IObject & object_;
};

} // namespace meumeu
} // namespace org

#endif
